services:
  app:
    image: package-search
    restart: always
    ports:
      - "8080:8080"

  nginx:
    image: my-nginx
    restart: always
    ports:
      - "80:80"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_USER=mypostgres
      - POSTGRES_PASSWORD=mypostgres

volumes:
  postgres-data: