services:
  code-scout:
    build:
      context: ../code-scout-deployment
    image: code-scout
    restart: always
    ports:
      - "8080:8080"

  cs-nginx:
    build:
      context: ../nginx-deployment
    image: cs-nginx
    restart: always
    ports:
      - "80:80"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=code-scout

volumes:
  postgres-data:
